// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsNoUserServerInfo(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_USER_SERVER_INFO.String() && e.Code == 1
}

func ErrorNoUserServerInfo(format string, args ...interface{}) *errors.Error {
	return errors.New(1, ErrorReason_NO_USER_SERVER_INFO.String(), fmt.Sprintf(format, args...))
}

func IsNoServerInfo(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_SERVER_INFO.String() && e.Code == 2
}

func ErrorNoServerInfo(format string, args ...interface{}) *errors.Error {
	return errors.New(2, ErrorReason_NO_SERVER_INFO.String(), fmt.Sprintf(format, args...))
}
