// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: pkg/res/resultobj.proto

package res

import (
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 动态类型data
type ResultObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResultObj) Reset() {
	*x = ResultObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_res_resultobj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultObj) ProtoMessage() {}

func (x *ResultObj) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_res_resultobj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultObj.ProtoReflect.Descriptor instead.
func (*ResultObj) Descriptor() ([]byte, []int) {
	return file_pkg_res_resultobj_proto_rawDescGZIP(), []int{0}
}

func (x *ResultObj) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResultObj) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResultObj) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResultObjString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResultObjString) Reset() {
	*x = ResultObjString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_res_resultobj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultObjString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultObjString) ProtoMessage() {}

func (x *ResultObjString) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_res_resultobj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultObjString.ProtoReflect.Descriptor instead.
func (*ResultObjString) Descriptor() ([]byte, []int) {
	return file_pkg_res_resultobj_proto_rawDescGZIP(), []int{1}
}

func (x *ResultObjString) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResultObjString) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResultObjString) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResultObjInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data int64  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResultObjInt64) Reset() {
	*x = ResultObjInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_res_resultobj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultObjInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultObjInt64) ProtoMessage() {}

func (x *ResultObjInt64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_res_resultobj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultObjInt64.ProtoReflect.Descriptor instead.
func (*ResultObjInt64) Descriptor() ([]byte, []int) {
	return file_pkg_res_resultobj_proto_rawDescGZIP(), []int{2}
}

func (x *ResultObjInt64) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResultObjInt64) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResultObjInt64) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_pkg_res_resultobj_proto protoreflect.FileDescriptor

var file_pkg_res_resultobj_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x6f, 0x62, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6b, 0x67, 0x2e, 0x72,
	0x65, 0x73, 0x1a, 0x25, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x09, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4f, 0x62, 0x6a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a,
	0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x13, 0x5a, 0x11, 0x6d, 0x68, 0x64, 0x73, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73,
	0x3b, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_res_resultobj_proto_rawDescOnce sync.Once
	file_pkg_res_resultobj_proto_rawDescData = file_pkg_res_resultobj_proto_rawDesc
)

func file_pkg_res_resultobj_proto_rawDescGZIP() []byte {
	file_pkg_res_resultobj_proto_rawDescOnce.Do(func() {
		file_pkg_res_resultobj_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_res_resultobj_proto_rawDescData)
	})
	return file_pkg_res_resultobj_proto_rawDescData
}

var file_pkg_res_resultobj_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_res_resultobj_proto_goTypes = []interface{}{
	(*ResultObj)(nil),       // 0: pkg.res.ResultObj
	(*ResultObjString)(nil), // 1: pkg.res.ResultObjString
	(*ResultObjInt64)(nil),  // 2: pkg.res.ResultObjInt64
	(*any.Any)(nil),         // 3: google.protobuf.Any
}
var file_pkg_res_resultobj_proto_depIdxs = []int32{
	3, // 0: pkg.res.ResultObj.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_res_resultobj_proto_init() }
func file_pkg_res_resultobj_proto_init() {
	if File_pkg_res_resultobj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_res_resultobj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_res_resultobj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultObjString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_res_resultobj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultObjInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_res_resultobj_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_res_resultobj_proto_goTypes,
		DependencyIndexes: file_pkg_res_resultobj_proto_depIdxs,
		MessageInfos:      file_pkg_res_resultobj_proto_msgTypes,
	}.Build()
	File_pkg_res_resultobj_proto = out.File
	file_pkg_res_resultobj_proto_rawDesc = nil
	file_pkg_res_resultobj_proto_goTypes = nil
	file_pkg_res_resultobj_proto_depIdxs = nil
}
